const GETALLDAFTARPENGELUARANKELUARGA = '/getAllProduct';
const ADDDAFTARPENGELUARANKELUARGA = '/addDaftarPengeluaranKeluarga';
const UPDATEDAFTARPENGELUARANKELUARGA = '/updateDaftarPengeluaranKeluarga';
const DELETEDAFTARPENGELUARANKELUARGA = '/deleteDaftarPengeluaranKeluarga';

export default {
  GETALLDAFTARPENGELUARANKELUARGA,
  ADDDAFTARPENGELUARANKELUARGA,
  UPDATEDAFTARPENGELUARANKELUARGA,
  DELETEDAFTARPENGELUARANKELUARGA,
};
