const GETALLPRODUCT = '/getAllProduct';
const ADDPRODUCT = '/addProduct';
const UPDATEPRODUCT = '/updateProduct';
const DELETEPRODUCT = '/deleteProduct';

const GETALLPARAMETERGROUP = '/getAllParameterGroup';
const GETALLPARAMETERGROUPBYPRODUCTID = '/getAllParameterGroupByProductId';
const ADDPARAMETERGROUP = '/addParameterGroup';
const UPDATEPARAMETERGROUP = '/updateParameterGroup';
const DELETEPARAMETERGROUP = '/deleteParameterGroup';

const GETALLPARAMETER = '/getAllParameter';
const ADDPARAMETER = '/addParameter';

const GETALLPRODUCTPARAMETER = '/getAllProductParameter';
const SETUPPRODUCTPARAMETER = '/setupProductParameter';

const GETALLPARAMETERVALUEBYPARAMETERID = '/getAllParameterValueByParameterId';
const SETUPPARAMETERVALUE = '/setupParameterValue';

export default {
  GETALLPRODUCT,
  ADDPRODUCT,
  UPDATEPRODUCT,
  DELETEPRODUCT,

  GETALLPARAMETERGROUP,
  GETALLPARAMETERGROUPBYPRODUCTID,
  ADDPARAMETERGROUP,
  UPDATEPARAMETERGROUP,
  DELETEPARAMETERGROUP,

  GETALLPARAMETER,
  ADDPARAMETER,

  GETALLPRODUCTPARAMETER,
  SETUPPRODUCTPARAMETER,

  GETALLPARAMETERVALUEBYPARAMETERID,
  SETUPPARAMETERVALUE,
};
